//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.20 at 03:34:28 PM MSK 
//


package ru.demo.debtors.soap.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AMList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AMList"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AMList" type="{http://tempuri.org/}ArrayOfArbitrManagerRegisterItem" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AMList", propOrder = {
    "amList"
})
public class AMList {

    @XmlElement(name = "AMList")
    protected ArrayOfArbitrManagerRegisterItem amList;

    /**
     * Gets the value of the amList property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfArbitrManagerRegisterItem }
     *     
     */
    public ArrayOfArbitrManagerRegisterItem getAMList() {
        return amList;
    }

    /**
     * Sets the value of the amList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfArbitrManagerRegisterItem }
     *     
     */
    public void setAMList(ArrayOfArbitrManagerRegisterItem value) {
        this.amList = value;
    }

}
