//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.09 at 05:49:42 PM MSK 
//


package ru.demo.debtors.soap.bindings;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DebtorCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DebtorCodeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CompanyInn"/&gt;
 *     &lt;enumeration value="PersonInn"/&gt;
 *     &lt;enumeration value="Ogrn"/&gt;
 *     &lt;enumeration value="Ogrnip"/&gt;
 *     &lt;enumeration value="Snils"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "DebtorCodeType")
@XmlEnum
public enum DebtorCodeType {

    @XmlEnumValue("CompanyInn")
    COMPANY_INN("CompanyInn"),
    @XmlEnumValue("PersonInn")
    PERSON_INN("PersonInn"),
    @XmlEnumValue("Ogrn")
    OGRN("Ogrn"),
    @XmlEnumValue("Ogrnip")
    OGRNIP("Ogrnip"),
    @XmlEnumValue("Snils")
    SNILS("Snils");
    private final String value;

    DebtorCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DebtorCodeType fromValue(String v) {
        for (DebtorCodeType c: DebtorCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
