//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.06 at 06:19:11 PM MSK 
//


package ru.demo.debtors.soap.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="GetArbitrManagerRegisterResult" type="{http://tempuri.org/}AMList" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getArbitrManagerRegisterResult"
})
@XmlRootElement(name = "GetArbitrManagerRegisterResponse")
public class GetArbitrManagerRegisterResponse {

    @XmlElement(name = "GetArbitrManagerRegisterResult")
    protected AMList getArbitrManagerRegisterResult;

    /**
     * Gets the value of the getArbitrManagerRegisterResult property.
     * 
     * @return
     *     possible object is
     *     {@link AMList }
     *     
     */
    public AMList getGetArbitrManagerRegisterResult() {
        return getArbitrManagerRegisterResult;
    }

    /**
     * Sets the value of the getArbitrManagerRegisterResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link AMList }
     *     
     */
    public void setGetArbitrManagerRegisterResult(AMList value) {
        this.getArbitrManagerRegisterResult = value;
    }

}
