//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.09 at 05:49:42 PM MSK 
//


package ru.demo.debtors.soap.bindings;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.demo.debtors.soap.bindings package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.demo.debtors.soap.bindings
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetMessageIds }
     * 
     */
    public GetMessageIds createGetMessageIds() {
        return new GetMessageIds();
    }

    /**
     * Create an instance of {@link GetMessageIdsResponse }
     * 
     */
    public GetMessageIdsResponse createGetMessageIdsResponse() {
        return new GetMessageIdsResponse();
    }

    /**
     * Create an instance of {@link ArrayOfInt }
     * 
     */
    public ArrayOfInt createArrayOfInt() {
        return new ArrayOfInt();
    }

    /**
     * Create an instance of {@link GetMessageContent }
     * 
     */
    public GetMessageContent createGetMessageContent() {
        return new GetMessageContent();
    }

    /**
     * Create an instance of {@link GetMessageContentResponse }
     * 
     */
    public GetMessageContentResponse createGetMessageContentResponse() {
        return new GetMessageContentResponse();
    }

    /**
     * Create an instance of {@link GetTradeMessageContent }
     * 
     */
    public GetTradeMessageContent createGetTradeMessageContent() {
        return new GetTradeMessageContent();
    }

    /**
     * Create an instance of {@link GetTradeMessageContentResponse }
     * 
     */
    public GetTradeMessageContentResponse createGetTradeMessageContentResponse() {
        return new GetTradeMessageContentResponse();
    }

    /**
     * Create an instance of {@link GetTradeMessages }
     * 
     */
    public GetTradeMessages createGetTradeMessages() {
        return new GetTradeMessages();
    }

    /**
     * Create an instance of {@link GetTradeMessagesResponse }
     * 
     */
    public GetTradeMessagesResponse createGetTradeMessagesResponse() {
        return new GetTradeMessagesResponse();
    }

    /**
     * Create an instance of {@link ArrayOfTradePlace }
     * 
     */
    public ArrayOfTradePlace createArrayOfTradePlace() {
        return new ArrayOfTradePlace();
    }

    /**
     * Create an instance of {@link GetTradeMessagesByTrade }
     * 
     */
    public GetTradeMessagesByTrade createGetTradeMessagesByTrade() {
        return new GetTradeMessagesByTrade();
    }

    /**
     * Create an instance of {@link GetTradeMessagesByTradeResponse }
     * 
     */
    public GetTradeMessagesByTradeResponse createGetTradeMessagesByTradeResponse() {
        return new GetTradeMessagesByTradeResponse();
    }

    /**
     * Create an instance of {@link GetArbitrManagerRegister }
     * 
     */
    public GetArbitrManagerRegister createGetArbitrManagerRegister() {
        return new GetArbitrManagerRegister();
    }

    /**
     * Create an instance of {@link GetArbitrManagerRegisterResponse }
     * 
     */
    public GetArbitrManagerRegisterResponse createGetArbitrManagerRegisterResponse() {
        return new GetArbitrManagerRegisterResponse();
    }

    /**
     * Create an instance of {@link AMList }
     * 
     */
    public AMList createAMList() {
        return new AMList();
    }

    /**
     * Create an instance of {@link GetDebtorRegister }
     * 
     */
    public GetDebtorRegister createGetDebtorRegister() {
        return new GetDebtorRegister();
    }

    /**
     * Create an instance of {@link GetDebtorRegisterResponse }
     * 
     */
    public GetDebtorRegisterResponse createGetDebtorRegisterResponse() {
        return new GetDebtorRegisterResponse();
    }

    /**
     * Create an instance of {@link DebtorList }
     * 
     */
    public DebtorList createDebtorList() {
        return new DebtorList();
    }

    /**
     * Create an instance of {@link GetCompanyTradeOrganizerRegister }
     * 
     */
    public GetCompanyTradeOrganizerRegister createGetCompanyTradeOrganizerRegister() {
        return new GetCompanyTradeOrganizerRegister();
    }

    /**
     * Create an instance of {@link GetCompanyTradeOrganizerRegisterResponse }
     * 
     */
    public GetCompanyTradeOrganizerRegisterResponse createGetCompanyTradeOrganizerRegisterResponse() {
        return new GetCompanyTradeOrganizerRegisterResponse();
    }

    /**
     * Create an instance of {@link TradeOrganizerList }
     * 
     */
    public TradeOrganizerList createTradeOrganizerList() {
        return new TradeOrganizerList();
    }

    /**
     * Create an instance of {@link GetSroRegister }
     * 
     */
    public GetSroRegister createGetSroRegister() {
        return new GetSroRegister();
    }

    /**
     * Create an instance of {@link GetSroRegisterResponse }
     * 
     */
    public GetSroRegisterResponse createGetSroRegisterResponse() {
        return new GetSroRegisterResponse();
    }

    /**
     * Create an instance of {@link SROList }
     * 
     */
    public SROList createSROList() {
        return new SROList();
    }

    /**
     * Create an instance of {@link GetDebtorByIdBankrupt }
     * 
     */
    public GetDebtorByIdBankrupt createGetDebtorByIdBankrupt() {
        return new GetDebtorByIdBankrupt();
    }

    /**
     * Create an instance of {@link GetDebtorByIdBankruptResponse }
     * 
     */
    public GetDebtorByIdBankruptResponse createGetDebtorByIdBankruptResponse() {
        return new GetDebtorByIdBankruptResponse();
    }

    /**
     * Create an instance of {@link GetDebtorsByLastPublicationPeriod }
     * 
     */
    public GetDebtorsByLastPublicationPeriod createGetDebtorsByLastPublicationPeriod() {
        return new GetDebtorsByLastPublicationPeriod();
    }

    /**
     * Create an instance of {@link GetDebtorsByLastPublicationPeriodResponse }
     * 
     */
    public GetDebtorsByLastPublicationPeriodResponse createGetDebtorsByLastPublicationPeriodResponse() {
        return new GetDebtorsByLastPublicationPeriodResponse();
    }

    /**
     * Create an instance of {@link GetDebtorMessagesContentForPeriodByIdBankrupt }
     * 
     */
    public GetDebtorMessagesContentForPeriodByIdBankrupt createGetDebtorMessagesContentForPeriodByIdBankrupt() {
        return new GetDebtorMessagesContentForPeriodByIdBankrupt();
    }

    /**
     * Create an instance of {@link GetDebtorMessagesContentForPeriodByIdBankruptResponse }
     * 
     */
    public GetDebtorMessagesContentForPeriodByIdBankruptResponse createGetDebtorMessagesContentForPeriodByIdBankruptResponse() {
        return new GetDebtorMessagesContentForPeriodByIdBankruptResponse();
    }

    /**
     * Create an instance of {@link GetDebtorReportsContentForPeriodByIdBankrupt }
     * 
     */
    public GetDebtorReportsContentForPeriodByIdBankrupt createGetDebtorReportsContentForPeriodByIdBankrupt() {
        return new GetDebtorReportsContentForPeriodByIdBankrupt();
    }

    /**
     * Create an instance of {@link GetDebtorReportsContentForPeriodByIdBankruptResponse }
     * 
     */
    public GetDebtorReportsContentForPeriodByIdBankruptResponse createGetDebtorReportsContentForPeriodByIdBankruptResponse() {
        return new GetDebtorReportsContentForPeriodByIdBankruptResponse();
    }

    /**
     * Create an instance of {@link SearchDebtorByCode }
     * 
     */
    public SearchDebtorByCode createSearchDebtorByCode() {
        return new SearchDebtorByCode();
    }

    /**
     * Create an instance of {@link SearchDebtorByCodeResponse }
     * 
     */
    public SearchDebtorByCodeResponse createSearchDebtorByCodeResponse() {
        return new SearchDebtorByCodeResponse();
    }

    /**
     * Create an instance of {@link TradePlace }
     * 
     */
    public TradePlace createTradePlace() {
        return new TradePlace();
    }

    /**
     * Create an instance of {@link ArrayOfTrade }
     * 
     */
    public ArrayOfTrade createArrayOfTrade() {
        return new ArrayOfTrade();
    }

    /**
     * Create an instance of {@link Trade }
     * 
     */
    public Trade createTrade() {
        return new Trade();
    }

    /**
     * Create an instance of {@link ArrayOfTradeMessage }
     * 
     */
    public ArrayOfTradeMessage createArrayOfTradeMessage() {
        return new ArrayOfTradeMessage();
    }

    /**
     * Create an instance of {@link TradeMessage }
     * 
     */
    public TradeMessage createTradeMessage() {
        return new TradeMessage();
    }

    /**
     * Create an instance of {@link ArrayOfArbitrManagerRegisterItem }
     * 
     */
    public ArrayOfArbitrManagerRegisterItem createArrayOfArbitrManagerRegisterItem() {
        return new ArrayOfArbitrManagerRegisterItem();
    }

    /**
     * Create an instance of {@link ArbitrManagerRegisterItem }
     * 
     */
    public ArbitrManagerRegisterItem createArbitrManagerRegisterItem() {
        return new ArbitrManagerRegisterItem();
    }

    /**
     * Create an instance of {@link ArrayOfDateAffiliation }
     * 
     */
    public ArrayOfDateAffiliation createArrayOfDateAffiliation() {
        return new ArrayOfDateAffiliation();
    }

    /**
     * Create an instance of {@link DateAffiliation }
     * 
     */
    public DateAffiliation createDateAffiliation() {
        return new DateAffiliation();
    }

    /**
     * Create an instance of {@link ArrayOfChoice1 }
     * 
     */
    public ArrayOfChoice1 createArrayOfChoice1() {
        return new ArrayOfChoice1();
    }

    /**
     * Create an instance of {@link DebtorPerson }
     * 
     */
    public DebtorPerson createDebtorPerson() {
        return new DebtorPerson();
    }

    /**
     * Create an instance of {@link ArrayOfLegalCaseInfo }
     * 
     */
    public ArrayOfLegalCaseInfo createArrayOfLegalCaseInfo() {
        return new ArrayOfLegalCaseInfo();
    }

    /**
     * Create an instance of {@link LegalCaseInfo }
     * 
     */
    public LegalCaseInfo createLegalCaseInfo() {
        return new LegalCaseInfo();
    }

    /**
     * Create an instance of {@link DebtorCompany }
     * 
     */
    public DebtorCompany createDebtorCompany() {
        return new DebtorCompany();
    }

    /**
     * Create an instance of {@link ArrayOfString }
     * 
     */
    public ArrayOfString createArrayOfString() {
        return new ArrayOfString();
    }

    /**
     * Create an instance of {@link ArrayOfCompanyTradeOrganizerRegisterItem }
     * 
     */
    public ArrayOfCompanyTradeOrganizerRegisterItem createArrayOfCompanyTradeOrganizerRegisterItem() {
        return new ArrayOfCompanyTradeOrganizerRegisterItem();
    }

    /**
     * Create an instance of {@link CompanyTradeOrganizerRegisterItem }
     * 
     */
    public CompanyTradeOrganizerRegisterItem createCompanyTradeOrganizerRegisterItem() {
        return new CompanyTradeOrganizerRegisterItem();
    }

    /**
     * Create an instance of {@link ArrayOfSroRegisterItem }
     * 
     */
    public ArrayOfSroRegisterItem createArrayOfSroRegisterItem() {
        return new ArrayOfSroRegisterItem();
    }

    /**
     * Create an instance of {@link SroRegisterItem }
     * 
     */
    public SroRegisterItem createSroRegisterItem() {
        return new SroRegisterItem();
    }

}
